# For plugins, clone tmux plugin manager first
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
#

set -g mouse on
set -g status-position top

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @tmux-gruvbox-left-status-a '#S' # tmux's session name
set -g @tmux-gruvbox-right-status-x '%Y-%d-%m'
set -g @tmux-gruvbox 'dark'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'tmux-plugins/tmux-sidebar'

set-option -g default-terminal "rxvt-unicode-256color"

# preix + space to jump back to prev window
bind Space last-window

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

run '~/.tmux/plugins/tpm/tpm'
